import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'Receive job assignments, track progress, and complete tasks easily.':
              'Receive job assignments, track progress, and complete tasks easily.',
          'Log in and get started!': 'Log in and get started!',
          'Enter ID': 'Enter ID',
          'Enter your id': 'Enter your id',
          'Password': 'Password',
          'Enter your password': 'Enter your password',
          'Log In': 'Log In',
          'Welcome Back': 'Welcome Back',
          'Starting soon': 'Starting soon',
          'View Details': 'View Details',
          'Start Job': 'Start Job',
          'Compleated': 'Compleated',
          'Scheduled': 'Scheduled',
          'Today\'s Schedule': 'Today\'s Schedule',
          'Home': 'Home',
          'Notification': 'Notification',
          'Jobs': 'Jobs',
          'Profile': 'Profile',
          'All Jobs': 'All Jobs',
          'Compleate Jobs': 'Compleate Jobs',
          'Language': 'Language',
          'Change Password': 'Change Password',
          'Logout': 'Logout',
          'Personal Details:': 'Personal Details:',
          'Job Details:': 'Job Details:',
          'Administrative Info :': 'Administrative Info :',
          'Navigate': 'Navigate',
          'New Assignment': 'New Assignment',
          'Payment Rate': 'Payment Rate',
          'Estimated Duration': 'Estimated Duration',
          'hours': 'hours',
          'Admin Notes': 'Admin Notes',
          'Progress Checklist': 'Progress Checklist',
          'Required Tools': 'Required Tools',
          'Accept': 'Accept',
          'Decline': 'Decline',
          'Report Issue': 'Report Issue',
          'Upload Photo': 'Upload Photo',
        },
        'fr': {
          'Receive job assignments, track progress, and complete tasks easily.':
              'Recevez des missions, suivez les progrès et accomplissez les tâches facilement.',
          'Log in and get started!': 'Connectez-vous et commencez!',
          'Enter ID': 'Entrez l\'ID',
          'Enter your id': 'Entrez votre ID',
          'Password': 'Mot de passe',
          'Enter your password': 'Entrez votre mot de passe',
          'Log In': 'Se connecter',
          'Welcome Back': 'Bon retour',
          'Starting soon': 'Commence bientôt',
          'View Details': 'Voir les détails',
          'Start Job': 'Commencer le travail',
          'Compleated': 'Complété',
          'Scheduled': 'Programmé',
          'Today\'s Schedule': 'Le programme d\'aujourd\'hui',
          'Home': 'Accueil',
          'Notification': 'Notification',
          'Jobs': 'Emplois',
          'Profile': 'Profil',
          'All Jobs': 'Tous les emplois',
          'Compleate Jobs': 'Emplois terminés',
          'Language': 'Langue',
          'Change Password': 'Changer le mot de passe',
          'Logout': 'Se déconnecter',
          'Personal Details:': 'Détails personnels:',
          'Job Details:': 'Détails de l\'emploi:',
          'Administrative Info :': 'Infos administratives :',
          'Navigate': 'Naviguer',
          'New Assignment': 'Nouvelle mission',
          'Payment Rate': 'Taux de paiement',
          'Estimated Duration': 'Durée estimée',
          'hours': 'heures',
          'Admin Notes': 'Notes de l\'administrateur',
          'Progress Checklist': 'Liste de contrôle des progrès',
          'Required Tools': 'Outils nécessaires',
          'Accept': 'Accepter',
          'Decline': 'Décliner',
          'Report Issue': 'Signaler un problème',
          'Upload Photo': 'Télécharger une photo',
        },
        'nl': {
          'Receive job assignments, track progress, and complete tasks easily.':
              'Ontvang taakopdrachten, volg de voortgang en voltooi taken eenvoudig.',
          'Log in and get started!': 'Log in en begin!',
          'Enter ID': 'Voer ID in',
          'Enter your id': 'Voer je ID in',
          'Password': 'Wachtwoord',
          'Enter your password': 'Voer je wachtwoord in',
          'Log In': 'Inloggen',
          'Welcome Back': 'Welkom terug',
          'Starting soon': 'Begint binnenkort',
          'View Details': 'Bekijk details',
          'Start Job': 'Start werk',
          'Compleated': 'Voltooid',
          'Scheduled': 'Gepland',
          'Today\'s Schedule': 'Vandaag\'s schema',
          'Home': 'Home',
          'Notification': 'Melding',
          'Jobs': 'Banen',
          'Profile': 'Profiel',
          'All Jobs': 'Alle banen',
          'Compleate Jobs': 'Voltooide banen',
          'Language': 'Taal',
          'Change Password': 'Wachtwoord wijzigen',
          'Logout': 'Uitloggen',
          'Personal Details:': 'Persoonlijke gegevens:',
          'Job Details:': 'Taakdetails:',
          'Administrative Info :': 'Administratieve informatie :',
          'Navigate': 'Navigeren',
          'New Assignment': 'Nieuwe taak',
          'Payment Rate': 'Betalingspercentage',
          'Estimated Duration': 'Geschatte duur',
          'hours': 'uren',
          'Admin Notes': 'Beheerdersnotities',
          'Progress Checklist': 'Voortgangschecklist',
          'Required Tools': 'Vereiste tools',
          'Accept': 'Accepteren',
          'Decline': 'Afwijzen',
          'Report Issue': 'Probleem melden',
          'Upload Photo': 'Foto uploaden',
        },
      };
}
